// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_IsASCII
int c_IsASCII(String fileName);
RcppExport SEXP _pMineR_c_IsASCII(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type fileName(fileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(c_IsASCII(fileName));
    return rcpp_result_gen;
END_RCPP
}
// transitionsTime
List transitionsTime(NumericVector listaEventi, NumericVector tempiTransizione, int max_valore_evento);
RcppExport SEXP _pMineR_transitionsTime(SEXP listaEventiSEXP, SEXP tempiTransizioneSEXP, SEXP max_valore_eventoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type listaEventi(listaEventiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tempiTransizione(tempiTransizioneSEXP);
    Rcpp::traits::input_parameter< int >::type max_valore_evento(max_valore_eventoSEXP);
    rcpp_result_gen = Rcpp::wrap(transitionsTime(listaEventi, tempiTransizione, max_valore_evento));
    return rcpp_result_gen;
END_RCPP
}
// filterPatProcess
List filterPatProcess(DataFrame PatProcess, CharacterVector arrayEventiDaRimuovere, CharacterVector arrayEventiDaTenere, int eventColumnNumber);
RcppExport SEXP _pMineR_filterPatProcess(SEXP PatProcessSEXP, SEXP arrayEventiDaRimuovereSEXP, SEXP arrayEventiDaTenereSEXP, SEXP eventColumnNumberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type PatProcess(PatProcessSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type arrayEventiDaRimuovere(arrayEventiDaRimuovereSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type arrayEventiDaTenere(arrayEventiDaTenereSEXP);
    Rcpp::traits::input_parameter< int >::type eventColumnNumber(eventColumnNumberSEXP);
    rcpp_result_gen = Rcpp::wrap(filterPatProcess(PatProcess, arrayEventiDaRimuovere, arrayEventiDaTenere, eventColumnNumber));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pMineR_c_IsASCII", (DL_FUNC) &_pMineR_c_IsASCII, 1},
    {"_pMineR_transitionsTime", (DL_FUNC) &_pMineR_transitionsTime, 3},
    {"_pMineR_filterPatProcess", (DL_FUNC) &_pMineR_filterPatProcess, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_pMineR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
