# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_IsASCII <- function(fileName) {
    .Call('_pMineR_c_IsASCII', PACKAGE = 'pMineR', fileName)
}

transitionsTime <- function(listaEventi, tempiTransizione, max_valore_evento) {
    .Call('_pMineR_transitionsTime', PACKAGE = 'pMineR', listaEventi, tempiTransizione, max_valore_evento)
}

filterPatProcess <- function(PatProcess, arrayEventiDaRimuovere, arrayEventiDaTenere, eventColumnNumber) {
    .Call('_pMineR_filterPatProcess', PACKAGE = 'pMineR', PatProcess, arrayEventiDaRimuovere, arrayEventiDaTenere, eventColumnNumber)
}

